<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageFloatingVersionsEnabled>true</CentralPackageFloatingVersionsEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.401" />
    <PackageVersion Include="Novolis.Math.Geometry" Version="2026.1.*" />
    <PackageVersion Include="Silk.NET.GLFW" Version="2.23.0" />
    <PackageVersion Include="Silk.NET.Input" Version="2.23.0" />
    <PackageVersion Include="Silk.NET.Input.Common" Version="2.23.0" />
    <PackageVersion Include="Silk.NET.Input.Glfw" Version="2.23.0" />
    <PackageVersion Include="Silk.NET.OpenGL" Version="2.23.0" />
    <PackageVersion Include="Silk.NET.Windowing" Version="2.23.0" />
    <PackageVersion Include="Silk.NET.Windowing.Glfw" Version="2.23.0" />
    <PackageVersion Include="Silk.NET.Vulkan" Version="2.23.0" />
    <PackageVersion Include="Silk.NET.Shaderc" Version="2.23.0" />
    <PackageVersion Include="Silk.NET.Shaderc.Native" Version="2.23.0" />
    <PackageVersion Include="TUnit" Version="1.72.16" />
  </ItemGroup>
</Project>
