<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Novolis.Silk.Unit</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="TUnit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Novolis.Silk.Runtime\Novolis.Silk.Runtime.csproj" />
    <ProjectReference Include="..\..\src\Novolis.Silk.Game\Novolis.Silk.Game.csproj" />
    <ProjectReference Include="..\..\src\Novolis.Silk.Capture\Novolis.Silk.Capture.csproj" />
    <ProjectReference Include="..\..\src\Novolis.Silk.Compute\Novolis.Silk.Compute.csproj" />
  </ItemGroup>
</Project>
